export const CREATE_ORDER_ITEM_FAIL = 'CREATE_ORDER_ITEM_FAIL';
export const INVALID_INPUT_DISH_OPTION = 'INVALID_INPUT_DISH_OPTION';
export const UPDATE_ORDER_STATUS_INVALID_USER_ID =
  'UPDATE_ORDER_STATUS_INVALID_USER_ID';
export const INVALID_ORDER_STATUS = 'INVALID_ORDER_STATUS';
